version: '2'
services:
  nodejs:
    image: ghcr.io/watergis/vt-boilerplate:v1.2.3
    # build: .
    environment: 
     - db_user=$db_user
     - db_password=$db_password
     - db_host=$db_host
     - db_port=$db_port
     - db_name=$db_name
    volumes:
      - ./data:/tmp/src/data
      - ./public:/tmp/src/public
      - ./config.js:/tmp/src/config.js
      - ./config-search.js:/tmp/src/config-search.js
