version: '2'
services:
  nodejs:
    image: narwassco/vt:v0.0.2
    # build: .
    environment: 
     - db_user=postgres
     - db_password=$db_password
     - db_host=host.docker.internal
     - db_port=5432
    volumes:
      - ./data:/tmp/src/data
      - ./public:/tmp/src/public
      - ./config.js:/tmp/src/config.js
      - ./config-search.js:/tmp/src/config-search.js
